name: home_rental_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/1.png
   - assets/nighthillvilla.png
   - assets/8.png
   - assets/detail1.png
   - assets/Group 3.png
   - assets/profile.jpg
   - assets/popvilla5.jpeg
   - assets/10.jpg
   - assets/9.jpg
   - assets/7.jpg
   - assets/6.jpg
   - assets/5.jpg
   - assets/3.jpg
   - assets/4.jpg
   - assets/2.jpg
   - assets/near_by_you/12.jpg
   - assets/near_by_you/13.jpg
   - assets/near_by_you/14.jpg
   - assets/razorpay.com.png