name: bicycle_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/cycleicon.png
   - assets/cycle1.png
   - assets/arrow.png
   - assets/search_home.png
   - assets/bicycle/1.png
   - assets/bicycle/2.png
   - assets/bicycle/3.png
   - assets/bicycle/4.png
   - assets/bicycle/5.png
   - assets/item_image/item1.png
   - assets/item_image/item2.png
   - assets/item_image/item3.png
   - assets/item_image/item4.png
   - assets/botton_navigation/1.png
   - assets/botton_navigation/2.png
   - assets/botton_navigation/3.png
   - assets/botton_navigation/4.png
   - assets/back (2).png