name: pet_care_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  stack: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/splashimage.png
   - assets/loginpage1.png
   - assets/dash1.png
   - assets/dash2.png
   - assets/category1.png
   - assets/category2.png
   - assets/category3.png
   - assets/category4.png
   - assets/dash community.png
   - assets/dashevent.png
   - assets/veternary/veternary1.png
   - assets/veternary/Vaccinations.png
   - assets/veternary/Operations.png
   - assets/veternary/Dentistry.png
   - assets/veternary/Behaviorals.png
   - assets/veternary/doctori.png
   - assets/doctordetail/doctor_detail.png
   - assets/grooming_image/groomin1.png
   - assets/shopimage/shop1.png