name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/home.png
   - assets/curseimage/gal1.png
   - assets/curseimage/resso.jpg
   - assets/curseimage/images.jpeg
   - assets/32.png
   - assets/11.png
   - assets/38.png
   - assets/39.png
   - assets/34.png
   - assets/40.png
   - assets/discography_song/image/1.jpg
   - assets/discography_song/image/21.jpg
   - assets/discography_song/image/3.jpg
   - assets/discography_song/image/heeriye.jpeg
   - assets/discography_song/image/Ram_siya_ram_im.jpg
   - assets/discography_song/image/maan_meri_jaanimage.jpg
   - assets/audio/
   - assets/curseimage/avenger.jpg
   - assets/curseimage/guitar.jpg
   - assets/curseimage/p1.jpeg
   - assets/curseimage/ragnarok.jpg
   - assets/curseimage/s3.jpg
   - assets/curseimage/s4.jpg
   - assets/curseimage/s5.jpg
   - assets/curseimage/s6.png
   - assets/curseimage/s8.jpg
   - assets/curseimage/s9.jpg
   - assets/curseimage/s11.jpg
   - assets/curseimage/s10.jpg
   - assets/curseimage/123.jpg
   - assets/image.jpg