name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/home.png
   - assets/curseimage/gal1.png
   - assets/curseimage/resso.jpg
   - assets/curseimage/images.jpeg
   - assets/32.png
   - assets/11.png
   - assets/38.png
   - assets/39.png
   - assets/34.png
   - assets/40.png
   - assets/
   - assets/discography_song/image/1.jpg
   - assets/discography_song/music/1.mp3
   - assets/discography_song/music/2.mp3
   - assets/discography_song/image/21.jpg
   - assets/discography_song/image/3.jpg
   - assets/discography_song/music/3.mp3
   - assets/discography_song/image/heeriye_image.jpg
   - assets/discography_song/image/Ram_siya_ram_im.jpg
   - assets/discography_song/image/maan_meri_jaanimage.jpg
   - assets/discography_song/music/Heeriye_song.mp3
   - assets/discography_song/music/Maan_meri_jaan.mp3
   - assets/discography_song/music/Ram_siya_Ram_song.mp3